services:
  backend:
    build: ./app/backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - flask_ai

  flask_ai:
    build:
      context: ./app/flask-ai
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
